
BASIC_LAND_NAMES = frozenset({"Plains", "Island", "Swamp", "Mountain", "Forest"})

VINTAGE_RESTRICTED_CARDS: set[str] = {
    "Ancestral Recall",
    "Balance",
    "Black Lotus",
    "Brainstorm",
    "Chalice of the Void",
    "Channel",
    "Demonic Consultation",
    "Demonic Tutor",
    "Dig through Time",
    "Flash",
    "Gitaxian Probe",
    "Golgari Grave-Troll",
    "Gush",
    "Imperial Seal",
    "Karn, the Great Creator",
    "Library of Alexandria",
    "Lion's Eye Diamond",
    "Lodestone Golem",
    "Lotus Petal",
    "Mana Crypt",
    "Mana Vault",
    "Memory Jar",
    "Mental Misstep",
    "Merchant Scroll",
    "Mind's Desire",
    "Monastery Mentor",
    "Mox Emerald",
    "Mox Jet",
    "Mox Pearl",
    "Mox Ruby",
    "Mox Sapphire",
    "Mystic Forge",
    "Mystical Tutor",
    "Narset, Parter of Veils",
    "Necropotence",
    "Sol Ring",
    "Strip Mine",
    "The Fantasticar",
    "Thorn of Amethyst",
    "Time Vault",
    "Time Walk",
    "Timetwister",
    "Tinker",
    "Tolarian Academy",
    "Treasure Cruise",
    "Trinisphere",
    "Urza's Saga",
    "Vampiric Tutor",
    "Vexing Bauble",
    "Wheel of Fortune",
    "Windfall",
    "Yawgmoth's Will",
}

UNLIMITED_QUANTITY_CARDS: set[str] = set(BASIC_LAND_NAMES) | {
    "Cid, Timeless Artificer",
    "Dragon's Approach",
    "Hare Apparent",
    "Persistent Petitioners",
    "Rat Colony",
    "Relentless Rats",
    "Shadowborn Apostle",
    "Slime Against Humanity",
    "Sphinx's Approach",
    "Tempest Hawk",
    "Templar Knight",
}
